# default configuration

baseURL = "https://anecdotalsmovie.com"
languageCode = "en-us"
theme = "thomson-hugo"
title = "Anecdotals"
summaryLength = "10"
paginate = 20


# Banner
[Languages.en.bio]
bg_image = "images/banner-shape.png"
title = "Anecdotals Movie: A compassionate exploration of the nuanced vaccine debate. While the vaccine debate grows more divided, those with adverse reactions get stuck in the middle."
image = "images/anecdotals.jpeg"


# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify/css/themify-icons.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.carousel.min.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.theme.default.min.css"
#[[params.plugins.css]]
#link = "plugins/animated-text/animated-text.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/owl-carousel/owl.carousel.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
#[[params.plugins.js]]
#link = "plugins/animated-text/animated-text.js"
#[[params.plugins.js]]
#link = "plugins/google-map/gmap.js"
[[params.plugins.js]]
link="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/js/fontawesome.min.js"

# menu
[[menu.main]]
name = "Home"
url = "/"
weight = 1



[[menu.main]]
name = "Resources"
url = "resources"
weight = 6

[[menu.main]]
name = "Screenings"
url = "screenings"
weight = 10

[[menu.main]]
name = "Donate"
url = "donate"
weight = 15

[[menu.main]]
name = "References"
url = "references"
weight = 4

# default parameters
[params]
home = "Home"
logo = "images/logo.png"
# contact info
mobile = ""
email = ""
address = ""
# meta description
author = ""
# description = "Marjorie Roswell is a freelance developer and nutrition educator. She is passionate about music, nature, and climate resilience."
# google analytics
google_analytics_id = "199716792-1"#/*"G-12N3B6CB0D"*/
# contact form action
contact_form_action = "https://formspree.io/f/xleveggq" # contact form works with : https://formspree.io
# copyright
copyright = "&copy; 2022 Anecdotals, LLC"

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# google map
[params.gmap]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = ""
map_longitude = ""
map_marker = "images/marker.png"

# social site
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/sharer.php?u=http%3A%2F%2Fanectodalsmovie.com&t=thisissharetext"

[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/intent/tweet?url=https%3A%2F%2Fwww.anecdotalsmovie.com%2F&text=%22Anecdotals%22%20Movie%3A%20A%20compassionate%20exploration%20of%20the%20nuanced%20vaccine%20debate.+While+the+vaccine+debate+grows+more+divided%2C+those+with+adverse+reactions+get+stuck+in+the+middle."

[[params.social]]
icon = "fab fa-telegram-plane"
link = "https://t.me/share/url?url=https://anecdotalsmovie.com&text=%22Anecdotals%20Movie%22%20A%20compassionate%20exploration%20of%20the%20nuanced%20vaccine%20debate"

[[params.social]]
icon = "fab fa-whatsapp"
link = "https://api.whatsapp.com/send/?text=%22Anecdotals%20Movie%22%20A%20compassionate%20exploration%20of%20the%20nuanced%20vaccine%20debate.%20https%3A%2F%2Fwww.anecdotalsmovie.com&app_absent=0"



## disable categories
#[Taxonomies]
#tag = "tags"
#
#disableKinds = ["taxonomy"]

